### ISSUE TITLE
take a run at right click to paste

### ISSUE THREAD

**Issue by os-nicolas** [DeepwaterCreations/nomogaia-catalogue#100]

**Comment by DeepwaterCreations** [comment]
This is doable.
STUFF:
-Implement functions for the menu items
-Style the menu to match the rest of the program

**Comment by DeepwaterCreations** [comment]
window.getSelection() for getting selected text to copy.
The next step is to make it know where to put pasted text/which cut text to delete.

**Comment by DeepwaterCreations** [comment]
https://github.com/b1rdex/nw-contextmenu
Made it work with some help from this.
