### ISSUE TITLE
Only some list view rows are displaying

### ISSUE THREAD

**Issue by DeepwaterCreations** [DeepwaterCreations/nomogaia-catalogue#131]
If you scroll down in the list view, you quickly reach rows that never seem to stop being gray boxes.
I found the place where the transition between visible rows and non-rendered rows is. Scrolling up and down past it does not appear to change anything.

**Comment by DeepwaterCreations** [comment]
treeView.js has $scope.updateVisible(), which seems to make the appropriate rows visible (rowHat.onScreen set to true) when it's called.
Problem is, it isn't called when I scroll. It's called by other things, like switching between tree/list view. If I scroll to the divide between visible and not visible and click the list view toggle button, they recalculate appropriately.

**Comment by Colinwielga** [comment]
check line 211 of TreeView:
$("#tree-view .main .body").scroll(function () { $scope.updateVisible(true); })
maybe the selector: "#tree-view .main .body", is no longer good?

**Comment by DeepwaterCreations** [comment]
I think you're right. When I try to log the selector's matches to the console, I'm just getting an empty array.
On the other hand, the elements it's trying to match definitely exist. It seems like it should be a valid selector. 
Maybe this line is only hit when the ng-if in #tree-view is making that element not exist. That's what I'm looking into right now.

**Comment by DeepwaterCreations** [comment]
Yup, it was the ng-if.
