### ISSUE TITLE
Ctrl-S doesn't work

### ISSUE THREAD

**Issue by DeepwaterCreations** [DeepwaterCreations/nomogaia-catalogue#134]
Possibly it only doesn't work for me because I'm using Xmonad, and Xmonad is weird. @Colinwielga, if you have a moment, can you test if Ctrl-S saves properly in Windows?

**Comment by DeepwaterCreations** [comment]
Actually, there's no earthly reason why I can't just do that myself. Not like I don't HAVE Windows, I just don't use it for dev work.
Though I think I had problems getting it to run last time I tried in Windows.

**Comment by Colinwielga** [comment]
Ctrl + S works for me.

**Comment by DeepwaterCreations** [comment]
Excellent.
Maybe we don't need to worry about it, then? We could test it in OSX and KDE/Gnome, but 1. I'd expect Node to be UNIX-compatible first and Windows-compatible second, and 2. I'm not sure there's much we can do even if it doesn't work in one of those environments. Seems like it's failing in the Node libraries, not our code.

**Comment by Colinwielga** [comment]
I think we don't need to worry about it.

**Comment by DeepwaterCreations** [comment]
Cool. I'll close it.
