### ISSUE TITLE
Rights and Rightsholders drop spores on any fertile soil they pass over 

### ISSUE THREAD

**Issue by DeepwaterCreations** [DeepwaterCreations/nomogaia-catalogue#138]
If you drag a Right or Rightsholder over a data row on the way to dropping it on another data row, it will leave a clone behind in the data row it passed over. It's easy to accidentally add Rights and Rightsholders to the wrong row this way and maybe not even notice.

**Comment by DeepwaterCreations** [comment]
Basically, the "drop" part of drag and drop doesn't matter. Anything you drag the Rights over gets that Right.

**Comment by DeepwaterCreations** [comment]
@Colinwielga I have no idea how the drag and drop stuff works. Any thoughts? Might this be an easy fix?

**Comment by Colinwielga** [comment]
I am going to look in to this a little tomorrow night. I feel like I already fixed an issue very much like this.

do you want a tour of drag and drop?
