### ISSUE TITLE
sort matrix

### ISSUE THREAD

**Issue by os-nicolas** [DeepwaterCreations/nomogaia-catalogue#17]
by most impacted right or right-holder (I think kendyl wanted to be able to choose)
maybe use code form impacted rights

**Comment by DeepwaterCreations** [comment]
The impacted rights code is helpful, but won't solve this problem on its own.
Here's the plan: I'm going to make objects to store rows. Each row-object gets cell-html-strings associated with scores, and also an overall score. To sort rights-holders, I put the rows in an array and sort by row values. To sort rights, I get the scores for the cell in each row associated with that right, and add those up to get a column value.
(Ugh, this is so much stuff. Is there a simpler way to do this?)

**Comment by DeepwaterCreations** [comment]
Sorting rows is relatively easy. I can concatenate cell strings together to make a row-string, and I can sort the row strings before I add them to the table.
Columns will be harder. But let's start with rows.

**Comment by DeepwaterCreations** [comment]
Hmm... what if each row is an object mapping column headers to cell strings? Then for each row, I can iterate over a list of (potentially sorted) headers to add the cells in arbitrary column-order.

**Comment by DeepwaterCreations** [comment]
Almost have a basic setup working, but it isn't styling cells with scores and it isn't doing the hover thingy.

**Comment by DeepwaterCreations** [comment]
Okay, that's the basic framework working. I just need to add sorting and filtering.

**Comment by DeepwaterCreations** [comment]
It sorts by rows, at least.

**Comment by DeepwaterCreations** [comment]
I'm thinking maybe columns actually do get their own list of objects to match.

**Comment by DeepwaterCreations** [comment]
Oh - I want to sort this based on the most recent monitor, don't I.

**Comment by DeepwaterCreations** [comment]
PLAN: Give the row object extra fields taken from the newest monitor alongside the ones for the current monitor. Yeah? And we can leave the current monitor scores in for extra functionality.

**Comment by DeepwaterCreations** [comment]
Asking Kendyl about this. Le's see what she says.

**Comment by DeepwaterCreations** [comment]
Kendyl says to sort by lowest monitor, and absolute values is good.

**Comment by DeepwaterCreations** [comment]
Okay, I think the only thing left is the most obnoxious thing: Column sorting. My earlier comment that says I'll need column objects to do this is probably right.

**Comment by DeepwaterCreations** [comment]
Unlike rows, I have to get column data in piecemeal order. Um... maybe this will be reasonably painless if I start by filling an array with column objects, then adjust those values as I go through the loops for row data?

**Comment by DeepwaterCreations** [comment]
Okay, column sorting works!
BUT I'M NOT DONE YET.
The last thing I need is a gui switch to choose which to sort by.

**Comment by DeepwaterCreations** [comment]
jQueryUI's buttonset looks promising.

**Comment by DeepwaterCreations** [comment]
Okay, this is done! Huzzah! It's not terribly pretty, but that's an issue for later.
