### ISSUE TITLE
Colin does not don't like NO DATA

### ISSUE THREAD

**Issue by os-nicolas** [DeepwaterCreations/nomogaia-catalogue#51]
-The all caps makes me feel like i am being yelled at
-I want the message to be more descriptive 
-It maybe feels like an error message, when really it's not

**Comment by DeepwaterCreations** [comment]
NO DATA! NO DATA, COLIN! COLIN, DID YOU HEAR ME? *NO DATA*!!!

**Comment by DeepwaterCreations** [comment]
Hmm... but what should it say instead?

**Comment by DeepwaterCreations** [comment]
Okay, I de-capitalized it and added some extra text with instructions to add things to the catalogue.
