### ISSUE TITLE
add should not be selectable like a tab

### ISSUE THREAD

**Issue by os-nicolas** [DeepwaterCreations/nomogaia-catalogue#72]
![image](https://cloud.githubusercontent.com/assets/1789759/6356429/475f1198-bc2b-11e4-94ed-709c0b6e22b5.png)

to reproduce: click add and then click cancel

maybe Add should not be a tab, but a button?

**Comment by DeepwaterCreations** [comment]
I think at this point, turning Add into a button would be more trouble than it's worth. Though it probably wouldn't be too hard.
I'll set it so it re-selects the current monitor if you cancel.

**Comment by DeepwaterCreations** [comment]
Now It re-selects the current monitor if you cancel.
