### ISSUE TITLE
yoyoyo is not a good title

### ISSUE THREAD

**Issue by os-nicolas** [DeepwaterCreations/nomogaia-catalogue#95]

**Comment by DeepwaterCreations** [comment]
We might want to be able to add a * to the title when there are unsaved changes?
Or that might be above and beyond the call of duty. But it's something to consider when changing the title.

**Comment by DeepwaterCreations** [comment]
It is now "NomoGaia Catalog".
Dear Self: $("title") probably works just fine for the enhancement you had in mind.
