### ISSUE TITLE
save an empty catalog using all topics -> crash

### ISSUE THREAD

**Issue by os-nicolas** [DeepwaterCreations/nomogaia-catalogue#96]
does not appear to have to do with timing

**Comment by DeepwaterCreations** [comment]
Encoding issue...?

**Comment by DeepwaterCreations** [comment]
Quote marks issue...?

**Comment by DeepwaterCreations** [comment]
It all seems valid when I save it, up to and including an inspection of the output file.
Then when I load it, instead of JSON, it gets a pair of quotes with about three yards of whitespace between them.
So... I *think* it's a loading issue, but I don't really have any idea what's going on.

**Comment by DeepwaterCreations** [comment]
firstrow.sav has the same problem!

**Comment by DeepwaterCreations** [comment]
And so does secondrow.sav. Hmm.

**Comment by DeepwaterCreations** [comment]
http://jsonlint.com/ says this is valid JSON. I think maybe it's the node fs documentation I should be perusing.

**Comment by DeepwaterCreations** [comment]
It just isn't finishing the write, is all.
So I need to add a loop to save.

**Comment by DeepwaterCreations** [comment]
"save returned false" - and it keeps returning false. This "drain" thing doesn't seem to help. I need to figure out why it isn't working.

**Comment by DeepwaterCreations** [comment]
Or... what. I don't know. Is it not working? Is it just not finishing?

**Comment by DeepwaterCreations** [comment]
Turns out it doesn't matter how many rows have data, just whether or not it's the full-size table or the short one for testing.
So, yeah, I think it's just not finishing the file write.

**Comment by DeepwaterCreations** [comment]
Using the node.js function for doing a million writes gets the same error (I think) that my while loop version did:
Error: ENOSPC, write
at Error(native)

**Comment by DeepwaterCreations** [comment]
...which is because at that point, it has written ~4 GB of data to the file. (Which, as it happens, I can't examine in Notepad++ because it's too big.)

**Comment by DeepwaterCreations** [comment]
The JSON it's trying to write actually IS malformed - it cuts off in the middle of a word, and then there's a ton of whitespace.

**Comment by DeepwaterCreations** [comment]
But the JSON it saves is not malformed. It's the filew.write call that's broken.

**Comment by DeepwaterCreations** [comment]
But the JSON in the saved file isn't malformed, either. Unless there are more weird characters that we need to get rid of.

**Comment by DeepwaterCreations** [comment]
I think it's fixed! I just used a different set of saving and loading functions: Instead of screwing about with file streams, I just call fs.readFile and fs.writeFile.
